# fly.toml file generated for cockroach on 2021-09-17T14:26:39-07:00

app = "cockroach"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  Dockerfile = "Dockerfile"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 8080
  [[services.ports]]
    port = 10099


  # [[services.ports]]
    # port = 26257


[mounts]
source="roach1"
destination="/cockroach-data"
